/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package data_gui;

import ims.ui.report.MyiReportViewer;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Ananda_Ekanayake
 */
public class mainUI extends javax.swing.JFrame {

    /**
     * Creates new form mainUI
     */
    public mainUI() {
        initComponents();
        setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        repotsMenu = new javax.swing.JMenu();
        fullDetail = new javax.swing.JMenuItem();
        Search = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        repotsMenu.setText("Reports catagories");
        repotsMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        fullDetail.setText("Full detail list");
        fullDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullDetailActionPerformed(evt);
            }
        });
        repotsMenu.add(fullDetail);

        Search.setText("Search info. from file no.");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        repotsMenu.add(Search);

        jMenuItem2.setText("Back to the Main page");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        repotsMenu.add(jMenuItem2);

        menuBar.add(repotsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullDetailActionPerformed
       
        

      
            
        MyiReportViewer  mrv = new MyiReportViewer();
        mrv.generateReports("cea_datastore", null, 0);
        mrv.setBounds(0, 0, desktopPane.getWidth(), desktopPane.getHeight());
         mrv.setVisible(true);  
         desktopPane.add(mrv);
        
    }//GEN-LAST:event_fullDetailActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
       String input = JOptionPane.showInputDialog("Enter the file No");
        
            
                String fileno = new String(input);
                HashMap parameters = new HashMap();
                parameters.put("inputname", fileno);
                MyiReportViewer myiReportViewer = new MyiReportViewer();
                myiReportViewer.generateReports("cea_datastoref", parameters, 0);
                myiReportViewer.setBounds( 0, 0, desktopPane.getWidth(), desktopPane.getHeight());
                
                myiReportViewer.setVisible(true);
                desktopPane.add(myiReportViewer);
               
           
    }//GEN-LAST:event_SearchActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Search;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem fullDetail;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu repotsMenu;
    // End of variables declaration//GEN-END:variables

}
