/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package data_gui;

import data.data;
import data_dao.data_dao;
import data_dao.dbconnmanager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.View;

/**
 *
 * @author CHANDIMA
 */
public class my_data_GUI extends javax.swing.JFrame {

    /**
     *
     */
    public my_data_GUI() {
        initComponents();
        packData();
        
        
    }
    
    private void packData() {
        data_dao dao = new data_dao();
        ArrayList username = dao.packData();
        
        Iterator i = username.iterator();
        
        while (i.hasNext()) {
            cmbfile.addItem(i.next());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TXTDS = new javax.swing.JTextField();
        TXTGN = new javax.swing.JTextField();
        TXTE = new javax.swing.JTextField();
        TXTN = new javax.swing.JTextField();
        TXTOWNER = new javax.swing.JTextField();
        TXTINDUSTRY = new javax.swing.JTextField();
        TXTACTIVITY = new javax.swing.JTextField();
        TXTEMAIL = new javax.swing.JTextField();
        TXTEPLCATA = new javax.swing.JTextField();
        TXTAP = new javax.swing.JTextField();
        TXTADDRESS = new javax.swing.JTextField();
        TXTTELE = new javax.swing.JTextField();
        TXTBUISS = new javax.swing.JTextField();
        TXTLOCAL = new javax.swing.JTextField();
        TXTGSMD = new javax.swing.JTextField();
        TXTEPLNU = new javax.swing.JTextField();
        TXTDURATION = new javax.swing.JTextField();
        TXTWW = new javax.swing.JTextField();
        TXTSW = new javax.swing.JTextField();
        TXTNOICE = new javax.swing.JTextField();
        TXTHW = new javax.swing.JTextField();
        TXTAIR = new javax.swing.JTextField();
        TXTVIBRA = new javax.swing.JTextField();
        TXTPTA = new javax.swing.JTextField();
        TXTREMARK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cmbfile = new javax.swing.JComboBox();
        txtfile = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTADD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(153, 138, 138));
        jPanel1.setForeground(new java.awt.Color(0, 255, 0));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        TXTDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDSActionPerformed(evt);
            }
        });

        TXTGN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTGNActionPerformed(evt);
            }
        });

        TXTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEActionPerformed(evt);
            }
        });

        TXTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNActionPerformed(evt);
            }
        });

        TXTOWNER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTOWNERActionPerformed(evt);
            }
        });

        TXTINDUSTRY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTINDUSTRYActionPerformed(evt);
            }
        });

        TXTACTIVITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTACTIVITYActionPerformed(evt);
            }
        });

        TXTEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEMAILActionPerformed(evt);
            }
        });

        TXTEPLCATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEPLCATAActionPerformed(evt);
            }
        });

        TXTAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTAPActionPerformed(evt);
            }
        });

        TXTADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTADDRESSActionPerformed(evt);
            }
        });

        TXTTELE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTELEActionPerformed(evt);
            }
        });

        TXTBUISS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBUISSActionPerformed(evt);
            }
        });

        TXTLOCAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTLOCALActionPerformed(evt);
            }
        });

        TXTGSMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTGSMDActionPerformed(evt);
            }
        });

        TXTEPLNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEPLNUActionPerformed(evt);
            }
        });

        TXTDURATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDURATIONActionPerformed(evt);
            }
        });

        TXTWW.setText("                  ");
        TXTWW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTWWActionPerformed(evt);
            }
        });

        TXTSW.setText("                  ");
        TXTSW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSWActionPerformed(evt);
            }
        });

        TXTNOICE.setText("                                  ");
        TXTNOICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNOICEActionPerformed(evt);
            }
        });

        TXTHW.setText("                                                         ");
        TXTHW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTHWActionPerformed(evt);
            }
        });

        TXTAIR.setText("                               ");
        TXTAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTAIRActionPerformed(evt);
            }
        });

        TXTVIBRA.setText("                   ");
        TXTVIBRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTVIBRAActionPerformed(evt);
            }
        });

        TXTPTA.setText("                            ");
        TXTPTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPTAActionPerformed(evt);
            }
        });

        TXTREMARK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTREMARKActionPerformed(evt);
            }
        });

        jLabel1.setText("FILE NUMBER :");

        jLabel4.setText("E :");

        jLabel5.setText("DS DIVISION :");

        jLabel6.setText("N :");

        jLabel7.setText("GN DIVISION :");

        jLabel8.setText("OWNER'S NAME:");

        jLabel9.setText("INDUSTRY :");

        jLabel11.setText("ACTIVITY :");

        jLabel12.setText("EMAIL :");

        jLabel13.setText("EPL CATEGORY & NO.:");

        jLabel14.setText("AVAILABLE PERMIT/LICENSE EPL :");

        jLabel16.setText("ADDRESS :");

        jLabel15.setText("TELEPHONE NO. :");

        jLabel17.setText("BUI REGISTRATION :");

        jLabel18.setText("LOCAL AUTHORITY :");

        jLabel19.setText("G.S.M.D :");

        jLabel20.setText("EPL NUMBER :");

        jLabel21.setText("DURATION :");

        jLabel22.setText("WASTE WATER :");

        jLabel23.setText("SOLID WATER :");

        jLabel24.setText("HAZARDOUS WATER :");

        jLabel25.setText("AIR EMISSION:");

        jLabel26.setText("NOICE :");

        jLabel27.setText("VIBRATION :");

        jLabel28.setText("POLLUTION TREATMENT AVAILABILITY :");

        jLabel29.setText("REMARKS :");

        cmbfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbfileMouseClicked(evt);
            }
        });
        cmbfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbfileActionPerformed(evt);
            }
        });

        txtfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfileActionPerformed(evt);
            }
        });

        jButton3.setText("SEND SELECTED DATA INTO FILE NO.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setText("...................PLEASE CHOOSE THE CORRECT FILE NUMBER FROM FILE NO.CHOOSER BEFORE UPDATING OR DELETING HENSE IT IS VERY IMPORTANAT!!!!..............");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("FILE  NO. CHOOSER :");

        jLabel10.setText("VALUE YOU SELECTED :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTGSMD, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTEPLNU, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTACTIVITY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(TXTTELE, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(TXTEPLCATA, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTEMAIL)
                                    .addComponent(TXTAP)))
                            .addComponent(TXTREMARK)
                            .addComponent(TXTADDRESS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTAIR, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTDURATION)
                                    .addComponent(TXTBUISS))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel22)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(TXTWW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel26)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(TXTNOICE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel23)
                                                        .addGap(7, 7, 7)
                                                        .addComponent(TXTSW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel27)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TXTVIBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel24)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(TXTHW, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel28)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(TXTPTA))))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addComponent(TXTLOCAL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel18))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfile, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTGN)
                                    .addComponent(TXTINDUSTRY, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbfile, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(TXTADD)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))
                                    .addComponent(TXTDS)
                                    .addComponent(TXTOWNER)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(TXTE, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(TXTN))))
                            .addComponent(jTextField2))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel2)
                    .addComponent(TXTADD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1))
                    .addComponent(TXTDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TXTE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(TXTGN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TXTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTOWNER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(TXTINDUSTRY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTACTIVITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(TXTTELE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TXTEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(TXTEPLCATA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(TXTBUISS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(TXTLOCAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(TXTGSMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(TXTEPLNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TXTDURATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22)
                                        .addComponent(TXTWW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23)
                                        .addComponent(TXTSW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24)
                                        .addComponent(TXTHW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTAIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(TXTNOICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(TXTVIBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)
                                    .addComponent(TXTPTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTREMARK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(83, 186, 232));

        jButton2.setText("UPDATE ALREADY EXITING RECORDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("CHECK RECENT RECORDS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("<<BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setText("DELETE RECORDS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setText("PRINT RECORDS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton2)
                .addGap(38, 38, 38)
                .addComponent(jButton8)
                .addGap(29, 29, 29)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton6)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addGap(20, 20, 20))
        );

        jLabel30.setBackground(new java.awt.Color(204, 255, 204));
        jLabel30.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel30.setText("...................CENTRAL ENVIRONMANTAL AUTHORITY DATA COLLECTOR...................");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(250, 250, 250))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTREMARKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTREMARKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTREMARKActionPerformed
    
    private void TXTPTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPTAActionPerformed
    
    private void TXTVIBRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTVIBRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTVIBRAActionPerformed
    
    private void TXTAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTAIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTAIRActionPerformed
    
    private void TXTHWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTHWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTHWActionPerformed
    
    private void TXTNOICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOICEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOICEActionPerformed
    
    private void TXTSWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTSWActionPerformed
    
    private void TXTWWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTWWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTWWActionPerformed
    
    private void TXTDURATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDURATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDURATIONActionPerformed
    
    private void TXTEPLNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEPLNUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEPLNUActionPerformed
    
    private void TXTGSMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTGSMDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTGSMDActionPerformed
    
    private void TXTLOCALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTLOCALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTLOCALActionPerformed
    
    private void TXTBUISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBUISSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTBUISSActionPerformed
    
    private void TXTTELEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTELEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTELEActionPerformed
    
    private void TXTADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTADDRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTADDRESSActionPerformed
    
    private void TXTAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTAPActionPerformed
    
    private void TXTEPLCATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEPLCATAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEPLCATAActionPerformed
    
    private void TXTEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEMAILActionPerformed
    
    private void TXTACTIVITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTACTIVITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTACTIVITYActionPerformed
    
    private void TXTINDUSTRYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTINDUSTRYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTINDUSTRYActionPerformed
    
    private void TXTOWNERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTOWNERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTOWNERActionPerformed
    
    private void TXTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNActionPerformed
    
    private void TXTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEActionPerformed
    
    private void TXTGNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTGNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTGNActionPerformed
    
    private void TXTDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDSActionPerformed
        
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        String file = cmbfile.getSelectedItem().toString();
        String dsdivi = TXTDS.getText();
        String gn = TXTGN.getText();
        String e = TXTE.getText();
        String n = TXTN.getText();
        String indus = TXTINDUSTRY.getText();
        String own = TXTOWNER.getText();
        String address = TXTADDRESS.getText();
        String acti = TXTACTIVITY.getText();
        String tele = TXTTELE.getText();
        String mail = TXTEMAIL.getText();
        String eplc = TXTEPLCATA.getText();
        String ap = TXTAP.getText();
        String buiss = TXTBUISS.getText();
        String local = TXTLOCAL.getText();
        String gsmdp = TXTGSMD.getText();
        String ep = TXTEPLNU.getText();
        String dur = TXTDURATION.getText();
        String ww = TXTWW.getText();
        String sw = TXTSW.getText();
        String hw = TXTHW.getText();
        String air = TXTAIR.getText();
        String noi = TXTNOICE.getText();
        String vib = TXTVIBRA.getText();
        String pt = TXTPTA.getText();
        String rem = TXTREMARK.getText();
        
        data da = new data(file, dsdivi, gn, e, n, indus, own, address, acti, tele, mail, eplc, ap, buiss, local, gsmdp, ep, dur, ww, sw, hw, air, noi,
                vib, pt, rem);
        data_dao dao = new data_dao();        
        
        try {
            
            boolean result = dao.updateMember(da);
            System.out.println("result");
            if (result) {
                JOptionPane.showMessageDialog(this, "Update successful");
            } else {
                JOptionPane.showMessageDialog(this, "Update unsuccessful");
            }
            
            
            
            
            
            
            
            
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
        
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        data_gui.view_gui vi = new view_gui();
        
        vi.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        data_gui.my_data_dao gui = new my_data_dao();
        gui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void txtfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfileActionPerformed
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String add = TXTADD.getText();
        txtfile.setText(add);
         try {
            dbconnmanager dc = new dbconnmanager();
            ResultSet rs = dc.connect().createStatement().executeQuery("SELECT * FROM Store WHERE fileno ='" + cmbfile.getSelectedItem().toString() + "'");
            
            System.out.println("SELECT * FROM Store WHERE fileno ='" + cmbfile.getSelectedItem().toString() + "'");
            while (rs.next()) {                
                
                TXTDS.setText(rs.getString(2));
                TXTGN.setText(rs.getString(3));
                TXTE.setText(rs.getString(4));
                TXTN.setText(rs.getString(5));
                TXTINDUSTRY.setText(rs.getString(6));
                TXTOWNER.setText(rs.getString(7));
                TXTADDRESS.setText(rs.getString(8));
                TXTACTIVITY.setText(rs.getString(9));
                TXTTELE.setText(rs.getString(10));
                TXTEMAIL.setText(rs.getString(11));
                TXTEPLCATA.setText(rs.getString(12));
                TXTAP.setText(rs.getString(13));
                TXTBUISS.setText(rs.getString(14));
                TXTLOCAL.setText(rs.getString(15));
                TXTGSMD.setText(rs.getString(16));
                TXTEPLNU.setText(rs.getString(17));
                TXTDURATION.setText(rs.getString(18));
                TXTWW.setText(rs.getString(19));
                TXTSW.setText(rs.getString(20));
                TXTHW.setText(rs.getString(21));
                TXTAIR.setText(rs.getString(22));
                TXTNOICE.setText(rs.getString(23));
                TXTVIBRA.setText(rs.getString(24));
                TXTPTA.setText(rs.getString(25));
                TXTREMARK.setText(rs.getString(26));
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(my_data_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void cmbfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbfileActionPerformed
        
        String addto = (String) cmbfile.getSelectedItem();
        TXTADD.setText(addto);
        
      }//GEN-LAST:event_cmbfileActionPerformed
    
    private void cmbfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbfileMouseClicked
        try {
            dbconnmanager dc = new dbconnmanager();
            ResultSet rs = dc.connect().createStatement().executeQuery("SELECT * FROM Store WHERE fileno ='" + cmbfile.getSelectedItem().toString() + "'");
            
            System.out.println("SELECT * FROM Store WHERE fileno ='" + cmbfile.getSelectedItem().toString() + "'");
            while (rs.next()) {                
                
                TXTDS.setText(rs.getString(2));
                TXTGN.setText(rs.getString(3));
                TXTE.setText(rs.getString(4));
                TXTN.setText(rs.getString(5));
                TXTINDUSTRY.setText(rs.getString(6));
                TXTOWNER.setText(rs.getString(7));
                TXTADDRESS.setText(rs.getString(8));
                TXTACTIVITY.setText(rs.getString(9));
                TXTTELE.setText(rs.getString(10));
                TXTEMAIL.setText(rs.getString(11));
                TXTEPLCATA.setText(rs.getString(12));
                TXTAP.setText(rs.getString(13));
                TXTBUISS.setText(rs.getString(14));
                TXTLOCAL.setText(rs.getString(15));
                TXTGSMD.setText(rs.getString(16));
                TXTEPLNU.setText(rs.getString(17));
                TXTDURATION.setText(rs.getString(18));
                TXTWW.setText(rs.getString(19));
                TXTSW.setText(rs.getString(20));
                TXTHW.setText(rs.getString(21));
                TXTAIR.setText(rs.getString(22));
                TXTNOICE.setText(rs.getString(23));
                TXTVIBRA.setText(rs.getString(24));
                TXTPTA.setText(rs.getString(25));
                TXTREMARK.setText(rs.getString(26));
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(my_data_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_cmbfileMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String name = txtfile.getText();

        data data = new data(name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
        data_dao dao = new data_dao();
        try {
            boolean result = dao.delMember(data);

            if (result) {
                JOptionPane.showMessageDialog(this, "Delete successful");

            } else {
                JOptionPane.showMessageDialog(this, "Delete unsuccessful");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mainUI main = new mainUI();
        main.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(my_data_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(my_data_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(my_data_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(my_data_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new my_data_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTACTIVITY;
    private javax.swing.JTextField TXTADD;
    private javax.swing.JTextField TXTADDRESS;
    private javax.swing.JTextField TXTAIR;
    private javax.swing.JTextField TXTAP;
    private javax.swing.JTextField TXTBUISS;
    private javax.swing.JTextField TXTDS;
    private javax.swing.JTextField TXTDURATION;
    private javax.swing.JTextField TXTE;
    private javax.swing.JTextField TXTEMAIL;
    private javax.swing.JTextField TXTEPLCATA;
    private javax.swing.JTextField TXTEPLNU;
    private javax.swing.JTextField TXTGN;
    private javax.swing.JTextField TXTGSMD;
    private javax.swing.JTextField TXTHW;
    private javax.swing.JTextField TXTINDUSTRY;
    private javax.swing.JTextField TXTLOCAL;
    private javax.swing.JTextField TXTN;
    private javax.swing.JTextField TXTNOICE;
    private javax.swing.JTextField TXTOWNER;
    private javax.swing.JTextField TXTPTA;
    private javax.swing.JTextField TXTREMARK;
    private javax.swing.JTextField TXTSW;
    private javax.swing.JTextField TXTTELE;
    private javax.swing.JTextField TXTVIBRA;
    private javax.swing.JTextField TXTWW;
    private javax.swing.JComboBox cmbfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtfile;
    // End of variables declaration//GEN-END:variables
}
