/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package data_gui;

import data.data;
import data_dao.data_dao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.View;

/**
 *
 * @author CHANDIMA
 */
public class my_data_dao extends javax.swing.JFrame {

    /**
     * Creates new form my_data_dao
     */
    public my_data_dao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TXTFILE = new javax.swing.JTextField();
        TXTDS = new javax.swing.JTextField();
        TXTGN = new javax.swing.JTextField();
        TXTE = new javax.swing.JTextField();
        TXTN = new javax.swing.JTextField();
        TXTOWNER = new javax.swing.JTextField();
        TXTINDUSTRY = new javax.swing.JTextField();
        TXTACTIVITY = new javax.swing.JTextField();
        TXTEMAIL = new javax.swing.JTextField();
        TXTEPLCATA = new javax.swing.JTextField();
        TXTAP = new javax.swing.JTextField();
        TXTADDRESS = new javax.swing.JTextField();
        TXTTELE = new javax.swing.JTextField();
        TXTBUISS = new javax.swing.JTextField();
        TXTLOCAL = new javax.swing.JTextField();
        TXTGSMD = new javax.swing.JTextField();
        TXTEPLNU = new javax.swing.JTextField();
        TXTDURATION = new javax.swing.JTextField();
        TXTREMARK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        rbtnwwy = new javax.swing.JRadioButton();
        rbtnwwn = new javax.swing.JRadioButton();
        rbtnswy = new javax.swing.JRadioButton();
        rbtnswn = new javax.swing.JRadioButton();
        rbtnhwn = new javax.swing.JRadioButton();
        rbtnhwy = new javax.swing.JRadioButton();
        rbtnairy = new javax.swing.JRadioButton();
        rbtnairn = new javax.swing.JRadioButton();
        rbtnnoiy = new javax.swing.JRadioButton();
        rbtnnoin = new javax.swing.JRadioButton();
        rbtnviby = new javax.swing.JRadioButton();
        rbtnvibn = new javax.swing.JRadioButton();
        rbtnpoly = new javax.swing.JRadioButton();
        rbtnpoln = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(153, 138, 138));
        jPanel1.setForeground(new java.awt.Color(0, 255, 0));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        TXTFILE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFILEActionPerformed(evt);
            }
        });

        TXTDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDSActionPerformed(evt);
            }
        });

        TXTGN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTGNActionPerformed(evt);
            }
        });

        TXTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEActionPerformed(evt);
            }
        });

        TXTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNActionPerformed(evt);
            }
        });

        TXTOWNER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTOWNERActionPerformed(evt);
            }
        });

        TXTINDUSTRY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTINDUSTRYActionPerformed(evt);
            }
        });

        TXTACTIVITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTACTIVITYActionPerformed(evt);
            }
        });

        TXTEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEMAILActionPerformed(evt);
            }
        });

        TXTEPLCATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEPLCATAActionPerformed(evt);
            }
        });

        TXTAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTAPActionPerformed(evt);
            }
        });

        TXTADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTADDRESSActionPerformed(evt);
            }
        });

        TXTTELE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTELEActionPerformed(evt);
            }
        });

        TXTBUISS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBUISSActionPerformed(evt);
            }
        });

        TXTLOCAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTLOCALActionPerformed(evt);
            }
        });

        TXTGSMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTGSMDActionPerformed(evt);
            }
        });

        TXTEPLNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEPLNUActionPerformed(evt);
            }
        });

        TXTDURATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDURATIONActionPerformed(evt);
            }
        });

        TXTREMARK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTREMARKActionPerformed(evt);
            }
        });

        jLabel1.setText("FILE NUMBER :");

        jLabel4.setText("E :");

        jLabel5.setText("DS DIVISION :");

        jLabel6.setText("N :");

        jLabel7.setText("GN DIVISION :");

        jLabel8.setText("OWNER'S NAME:");

        jLabel9.setText("INDUSTRY :");

        jLabel11.setText("ACTIVITY :");

        jLabel12.setText("EMAIL :");

        jLabel13.setText("EPL CATEGORY & NO.:");

        jLabel14.setText("AVAILABLE PERMIT/LICENSE EPL :");

        jLabel16.setText("ADDRESS :");

        jLabel15.setText("TELEPHONE NO. :");

        jLabel17.setText("BUI REGISTRATION :");

        jLabel18.setText("LOCAL AUTHORITY :");

        jLabel19.setText("G.S.M.D :");

        jLabel20.setText("EPL NUMBER :");

        jLabel21.setText("DURATION :");

        jLabel22.setText("WASTE WATER :");

        jLabel23.setText("SOLID WATER :");

        jLabel24.setText("HAZARDOUS WATER :");

        jLabel25.setText("AIR EMISSION:");

        jLabel26.setText("NOICE :");

        jLabel27.setText("VIBRATION :");

        jLabel28.setText("POLLUTION TREATMENT AVAILABILITY :");

        jLabel29.setText("REMARKS :");

        buttonGroup1.add(rbtnwwy);
        rbtnwwy.setText(" Yes");

        buttonGroup1.add(rbtnwwn);
        rbtnwwn.setText(" No ");

        buttonGroup2.add(rbtnswy);
        rbtnswy.setText(" Yes");

        buttonGroup2.add(rbtnswn);
        rbtnswn.setText(" No ");

        buttonGroup3.add(rbtnhwn);
        rbtnhwn.setText(" No ");

        buttonGroup3.add(rbtnhwy);
        rbtnhwy.setText(" Yes");

        buttonGroup4.add(rbtnairy);
        rbtnairy.setText(" Yes");

        buttonGroup4.add(rbtnairn);
        rbtnairn.setText(" No");

        buttonGroup5.add(rbtnnoiy);
        rbtnnoiy.setText(" Yes");

        buttonGroup5.add(rbtnnoin);
        rbtnnoin.setText(" No");

        buttonGroup6.add(rbtnviby);
        rbtnviby.setText(" Yes");

        buttonGroup6.add(rbtnvibn);
        rbtnvibn.setText(" No ");

        buttonGroup7.add(rbtnpoly);
        rbtnpoly.setText(" Available");

        buttonGroup7.add(rbtnpoln);
        rbtnpoln.setText(" Not available");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel3)
                            .addGap(63, 63, 63)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel21)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTACTIVITY, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTADDRESS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXTINDUSTRY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(TXTGN, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTN, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTOWNER))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTFILE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TXTE, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(TXTDS, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTTELE, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTEMAIL))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TXTEPLCATA, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TXTBUISS, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TXTLOCAL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTGSMD, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTEPLNU, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TXTAP)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTDURATION, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTREMARK))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbtnwwy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnwwn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbtnnoiy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnnoin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbtnswy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnswn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnhwy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnhwn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnairy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnairn))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbtnviby)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnvibn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnpoly)
                                .addGap(6, 6, 6)
                                .addComponent(rbtnpoln)))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTFILE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(TXTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTGN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TXTOWNER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(TXTINDUSTRY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTACTIVITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTTELE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TXTEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTEPLCATA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(TXTAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTBUISS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(TXTLOCAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(TXTGSMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(TXTEPLNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTDURATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel29)
                    .addComponent(TXTREMARK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnwwy)
                    .addComponent(jLabel22)
                    .addComponent(rbtnwwn)
                    .addComponent(jLabel23)
                    .addComponent(rbtnswy)
                    .addComponent(rbtnswn)
                    .addComponent(jLabel24)
                    .addComponent(rbtnhwy)
                    .addComponent(rbtnhwn)
                    .addComponent(jLabel25)
                    .addComponent(rbtnairy)
                    .addComponent(rbtnairn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnnoiy)
                        .addComponent(rbtnnoin)
                        .addComponent(jLabel27)
                        .addComponent(rbtnviby)
                        .addComponent(rbtnvibn)
                        .addComponent(jLabel28)
                        .addComponent(rbtnpoly)
                        .addComponent(rbtnpoln))
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(83, 186, 232));

        jButton1.setText("INSERT RECORDS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("CHECK RECENT RECORDS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("UPDATE/DELETE >>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setText("PRINT OR SEARCH INFORMATION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addComponent(jButton7)
                .addGap(57, 57, 57)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(39, 39, 39)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("...................CENTRAL ENVIRONMANTAL AUTHORITY DATA COLLECTOR...................");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTREMARKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTREMARKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTREMARKActionPerformed

    private void TXTDURATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDURATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDURATIONActionPerformed

    private void TXTEPLNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEPLNUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEPLNUActionPerformed

    private void TXTGSMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTGSMDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTGSMDActionPerformed

    private void TXTLOCALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTLOCALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTLOCALActionPerformed

    private void TXTBUISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBUISSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTBUISSActionPerformed

    private void TXTTELEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTELEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTELEActionPerformed

    private void TXTADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTADDRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTADDRESSActionPerformed

    private void TXTEPLCATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEPLCATAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEPLCATAActionPerformed

    private void TXTEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEMAILActionPerformed

    private void TXTACTIVITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTACTIVITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTACTIVITYActionPerformed

    private void TXTINDUSTRYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTINDUSTRYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTINDUSTRYActionPerformed

    private void TXTOWNERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTOWNERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTOWNERActionPerformed

    private void TXTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNActionPerformed

    private void TXTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEActionPerformed

    private void TXTGNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTGNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTGNActionPerformed

    private void TXTDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDSActionPerformed

    private void TXTFILEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFILEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFILEActionPerformed

    private void TXTAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTAPActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        data_gui.my_data_GUI guo = new my_data_GUI();
        guo . setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        data_gui.view_gui vi  = new view_gui ();

        vi.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String filen = TXTFILE.getText();
        String dsdivi = TXTDS.getText();
        String gn = TXTGN.getText();
        String e = TXTE.getText();
        String n = TXTN.getText();
        String indus = TXTINDUSTRY.getText();
        String own = TXTOWNER.getText();
        String address = TXTADDRESS.getText();
        String acti = TXTACTIVITY.getText();
        String tele = TXTTELE.getText();
        String mail = TXTEMAIL.getText();
        String eplc = TXTEPLCATA.getText();
        String ap = TXTAP.getText();
        String buiss = TXTBUISS.getText();
        String local = TXTLOCAL.getText();
        String gsmdp = TXTGSMD.getText();
        String ep = TXTEPLNU.getText();
        String dur = TXTDURATION.getText();
        String rem = TXTREMARK.getText();

        String ww = new String();
        String sw = new String();
        String hw = new String();
        String air = new String();
        String noi = new String();
        String vib = new String();
        String pt = new String();

        if(rbtnwwy.isSelected()){
            ww ="Yes";
        }
        if(rbtnwwn.isSelected()){
            ww="No";
        }
        System.out.println(ww);

        if(rbtnswy.isSelected()){
            sw ="Yes";
        }
        if(rbtnswn.isSelected()){
            sw="No";
        }
        System.out.println(sw);

        if(rbtnhwy.isSelected()){
            hw ="Yes";
        }
        if(rbtnhwn.isSelected()){
            hw="No";
        }
        System.out.println(hw);

        if(rbtnairy.isSelected()){
            air ="Yes";
        }
        if(rbtnairn.isSelected()){
            air="No";
        }
        System.out.println(air);

        if(rbtnnoiy.isSelected()){
            noi ="Yes";
        }
        if(rbtnnoin.isSelected()){
            noi="No";
        }
        System.out.println(noi);

        if(rbtnviby.isSelected()){
            vib ="Yes";
        }
        if(rbtnvibn.isSelected()){
            vib="No";
        }
        System.out.println(vib);

        if(rbtnpoly.isSelected()){
            pt ="Yes";
        }
        if(rbtnpoln.isSelected()){
            pt ="No";
        }
        System.out.println(pt);

        data da = new data(filen, dsdivi, gn, e, n, indus, own, address, acti, tele, mail, eplc, ap, buiss, local, gsmdp, ep, dur, ww, sw, hw, air, noi, vib, pt, rem);

        data_dao dao = new data_dao();

        try {
            boolean result = dao.addMember(da);
            if (result) {
                JOptionPane.showMessageDialog(this, "Data has been inserted successfully");

            } else {
                JOptionPane.showMessageDialog(this, "Data hasn't been inserted.ERROR!");
            }
        } catch (SQLException eb) {
            System.out.println(eb);

        }

        TXTFILE.setText("");
        TXTDS.setText("");
        TXTGN.setText("");
        TXTE.setText("");
        TXTN.setText("");
        TXTINDUSTRY.setText("");
        TXTOWNER.setText("");
        TXTADDRESS.setText("");
        TXTACTIVITY.setText("");
        TXTTELE.setText("");
        TXTEMAIL.setText("");
        TXTEPLCATA.setText("");

        TXTAP.setText("");
        TXTBUISS.setText("");
        TXTLOCAL.setText("");
        TXTGSMD.setText("");
        TXTEPLNU.setText("");
        TXTDURATION.setText("");

        TXTREMARK.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       mainUI main = new mainUI();
       main.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(my_data_dao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(my_data_dao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(my_data_dao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(my_data_dao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new my_data_dao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTACTIVITY;
    private javax.swing.JTextField TXTADDRESS;
    private javax.swing.JTextField TXTAP;
    private javax.swing.JTextField TXTBUISS;
    private javax.swing.JTextField TXTDS;
    private javax.swing.JTextField TXTDURATION;
    private javax.swing.JTextField TXTE;
    private javax.swing.JTextField TXTEMAIL;
    private javax.swing.JTextField TXTEPLCATA;
    private javax.swing.JTextField TXTEPLNU;
    private javax.swing.JTextField TXTFILE;
    private javax.swing.JTextField TXTGN;
    private javax.swing.JTextField TXTGSMD;
    private javax.swing.JTextField TXTINDUSTRY;
    private javax.swing.JTextField TXTLOCAL;
    private javax.swing.JTextField TXTN;
    private javax.swing.JTextField TXTOWNER;
    private javax.swing.JTextField TXTREMARK;
    private javax.swing.JTextField TXTTELE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton rbtnairn;
    private javax.swing.JRadioButton rbtnairy;
    private javax.swing.JRadioButton rbtnhwn;
    private javax.swing.JRadioButton rbtnhwy;
    private javax.swing.JRadioButton rbtnnoin;
    private javax.swing.JRadioButton rbtnnoiy;
    private javax.swing.JRadioButton rbtnpoln;
    private javax.swing.JRadioButton rbtnpoly;
    private javax.swing.JRadioButton rbtnswn;
    private javax.swing.JRadioButton rbtnswy;
    private javax.swing.JRadioButton rbtnvibn;
    private javax.swing.JRadioButton rbtnviby;
    private javax.swing.JRadioButton rbtnwwn;
    private javax.swing.JRadioButton rbtnwwy;
    // End of variables declaration//GEN-END:variables
}
